### ISSUE TITLE
NetworkOnMainThreadException with @OnBackground() ?

### ISSUE THREAD

**Issue by dasmikko** [Arasthel/SwissKnife#15]
I'm getting this error: ``android.os.NetworkOnMainThreadException``

When running this void:
```
@OnBackground()
    public void getArchive()
    {
        try
        {
            String baseUrl = "http://xkcd.com/archive/";
            Document doc  = Jsoup.connect(baseUrl).get();

            List<String> comics = new ArrayList<String>();

            Elements metaElems = doc.select("div#middleContainer a");
            for (Element item : metaElems)
            {
                Log.e("Item: ", item.attr("href"));
                comics.add("http:\\/\\/imgs.xkcd.com\\/comics\\/squirrel_plan.png");
            }

            updateViewPager(comics);

        }
        catch (IOException e)
        {

        }
    }
```

It shouldn't throw that error, since i'm running the network code in an background thread..

**Comment by eugene-kamenev** [comment]
@dasmikko can you please provide full source code of the class?

**Comment by dasmikko** [comment]
Sure!

```
public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getArchive();


    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    @OnBackground()
    public void getArchive()
    {
        try
        {
            String baseUrl = "http://xkcd.com/archive/";
            Document doc  = Jsoup.connect(baseUrl).get();

            List<String> comics = new ArrayList<String>();

            Elements metaElems = doc.select("div#middleContainer a");
            for (Element item : metaElems)
            {
                Log.e("Item: ", item.attr("href"));
                comics.add("http:\\/\\/imgs.xkcd.com\\/comics\\/squirrel_plan.png");
            }

            updateViewPager(comics);

        }
        catch (IOException e)
        {

        }
    }

    protected void updateViewPager(List<String> imageList)
    {
        ViewPager galleryImages = (ViewPager)findViewById(R.id.myViewPager);

        galleryImages.setAdapter(new GalleryPhotoViewAdapter(this, imageList));
    }
}

```

**Comment by eugene-kamenev** [comment]
You forgot to call 
SwissKnife.inject(this)

after

setContentView(R.layout.activity_main);

and just as suggestion, if you are using groovy, you can start using its cool syntax :)

**Comment by dasmikko** [comment]
Hmm, now I get this error :(
```
groovy.lang.MissingMethodException: No signature of method: com.ankerapps.xkcdmaterial.MainActivity.injectViews() is applicable for argument types: (com.ankerapps.xkcdmaterial.MainActivity) values: [com.ankerapps.xkcdmaterial.MainActivity@422f1f88]
```

**Comment by eugene-kamenev** [comment]
The first and second exceptions looks strange, lets wait what /cc @Arasthel will say

**Comment by Arasthel** [comment]
Sorry for the late reply, there are some connection issues on my area and my ISP hasn't fixed them yet. Actually, `SwissKnife.inject` shouldn't be necessary for this, the AST transformation is automatic.

I've just tried it out on a new Activity and everything works as it should. I think that the only way that exception could appear is if the AST transformation doesn't take place... 

Could you provide the whole exception?

**Comment by eugene-kamenev** [comment]
Yes, i missed it, SwissKnife.inject is not necessary, but the second exception is also strange, it cant be called in that way. @dasmikko you used .aar version of SwissKnife from maven?

**Comment by dasmikko** [comment]
I'm using the gradle version @eugene-kamenev 

Here @Arasthel 
```
03-26 17:29:09.250  13456-13456/com.ankerapps.xkcdmaterial E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ankerapps.xkcdmaterial, PID: 13456
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ankerapps.xkcdmaterial/com.ankerapps.xkcdmaterial.MainActivity}: groovy.lang.MissingMethodException: No signature of method: com.ankerapps.xkcdmaterial.MainActivity.injectViews() is applicable for argument types: (com.ankerapps.xkcdmaterial.MainActivity) values: [com.ankerapps.xkcdmaterial.MainActivity@42402cc0]
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: groovy.lang.MissingMethodException: No signature of method: com.ankerapps.xkcdmaterial.MainActivity.injectViews() is applicable for argument types: (com.ankerapps.xkcdmaterial.MainActivity) values: [com.ankerapps.xkcdmaterial.MainActivity@42402cc0]
            at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)
            at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
            at com.arasthel.swissknife.SwissKnife.inject(SwissKnife.groovy:39)
            at com.ankerapps.xkcdmaterial.MainActivity.onCreate(MainActivity.java:55)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)

```

**Comment by Arasthel** [comment]
Sorry, I meant the whole `NetworkOnMainThreadException`, this exception is normal as that method doesn't exist. As I said before, SwissKnife.inject() isn't necessary.

**Comment by dasmikko** [comment]
It's okay. :)

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ankerapps.xkcdmaterial/com.ankerapps.xkcdmaterial.MainActivity}: android.os.NetworkOnMainThreadException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
            at java.net.InetAddress.getAllByName(InetAddress.java:214)
            at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
            at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
            at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
            at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
            at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449)
            at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
            at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
            at org.jsoup.helper.HttpConnection.get(HttpConnection.java:170)
            at com.ankerapps.xkcdmaterial.MainActivity.getArchive(MainActivity.java:31)
            at com.ankerapps.xkcdmaterial.MainActivity.onCreate(MainActivity.java:56)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Arasthel** [comment]
Yes, as I suspected, the AST transformation isn't happening - there is no call to `getArchive$background` method, which should be autogenerated. You are using this on a `.groovy` file, right?

**Comment by dasmikko** [comment]
No? Should i? I'm pretty new to all this android dev stuff, and I just wanted a easier way to to background tasks.

**Comment by Arasthel** [comment]
Yes, you definitely should :wink. Please take a look at [this](https://github.com/Arasthel/SwissKnife/wiki/How-to-use-Groovy) to see how to configure everything. Also, if you just want that and prefer to stick with Java I would suggest you to use AndroidAnnotations. The problem with AndroidAnnotations is that you can have some inheritance problems with activities, but as long as your code isn't really complex you should be fine.

That said, Groovy is a great language, almost fully compatible with Java and lets you do stuff quick and easily, so it's your choice.

**Comment by eugene-kamenev** [comment]
But groovy ast should also happen on java classes as well

2015-03-26 23:32 GMT+06:00 Jorge Martin Espinosa <notifications@github.com>:

**Comment by eugene-kamenev** [comment]
@dasmikko I think I found what causes a problem. Just put your java sources under src/main/groovy folder. Groovy plug-in searches the needed sources there. And you can still use java as main language as well.
